### ISSUE TITLE
wtip-003 - misleading terminology

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wtips#10]
In the proposal 003, "Services" seems to be misleading terminology - we need to devise an idiomatic alternative.

**Comment by hynek-urban** [comment]
I have prepared two possible alternative solutions in the following two branches:

- *fix/wtip-003-rename-services*

Here, "services" are renamed to "flights", and the original "flights" are now "flight instances". (I believe this terminology is in line with what I've seen in NDC.) Other than that, the data structure remains the same.

- *fix/wtip-003-remove-services*

Here the "services" are renamed to "flights", the original "flights" document is removed and each flight number entry contains a "flightInstancesUri" for the given flight instead. This seems better than the previous alternative to me, however, having a reference like this does not work well with the current implementation of StoragePointer. If this was selected as the preferred form, the StoragePointer implementation in wt-js-libs would have to be extended first.

One of these alternatives should probably be adopted and the other one should be thrown away. There is also a third option, a middle ground - in the second variant, we could put all flightInstancesUris to a single top-level object (instead of putting it one by one to each flight record). In this way, we could utilize the existing StoragePointer implementation.

**Comment by ondrejchmelar** [comment]
Agredd, I went with `fix/wtip-003-remove-services` so FlightInstances are now children of Flights. 
Waiting in `feat/airline-platform` for other airline changes to me merged together.

**Comment by JirkaChadima** [comment]
@ondrejchmelar I believe we can close this particular issue, can't we? Or do we consider this to be a meta-issue waiting for other issues and PRs in other repositories?
