### ISSUE TITLE
Proving trustworthiness

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wtips#2]
# Idea

We want to prevent scammers from flooding the system with fake and impostor data.

# Pros

- Data quality is improved

# Cons

- More work for data owners (but ideally only once during registration)

# Proposals

- Human driven process (phone calls etc.) similar to [EV certification process](https://www.instantssl.com/ssl-certificate-products/ssl/ssl-ev-validation.html)
- Staking of Ether/LIF
- Proof of ownership based on [ACME challenges](https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.8)
- Using a [third party](https://www.mattereum.com/) service to verify real world asset owners, we can use video calls etc.
- We can also do a two step enrollment (the hotel will be activated on the platform only when a challenge is successfully responded)
- Token Curated Registry https://youtu.be/XlQgBYsXhds, https://medium.com/@ilovebagels/token-curated-registries-1-0-61a232f8dac7
- Trusted traveller reviews - when they leave a review for a company on the platform it counts as a confirmation that it's a legitimate business.
- Delayed payment - a new supplier requires a certain number of confirmed transactions before they receive the money
- reverse image search. One of the ways to reveal scam listings on AirBnB and Booking.com is to run the listing pictures through a service like https://tineye.com/
- trusted "sources" for verification (Google My Business, Booking.com,  AirBnb, hotels.com etc) - if a hotel posts their public key on it's page on those resources (e.g. at least on 2 websites) it will be verified.

**Comment by JirkaChadima** [comment]
This is remotely related: https://github.com/windingtree/wiki/issues/38

**Comment by czervenka** [comment]
Notes from discussion during planning:

Before we go to mainnet we need to setup some rules / tools to advantage fair players. There is wide spectrum of possible solutions. We decided to start of with something simple and extensible.

1. Líf Stake - We would like to allow Líf stake to help a real identity to stand out (from testing, fake, etc.). The exact parameters like amount, lockout duration for a stake, etc. are yet to be defined and most of it will be only a recommendation (in a computer friendly format).
2. Domain (URL) verification
3. Research other options to bind an identity in WT Index to real worl (EV Certificates, [KYC](https://en.wikipedia.org/wiki/Know_your_customer), Let's encrypt, ...)

@JirkaChadima is writing an article about this topic, we will link it here soon as well.

**Comment by JirkaChadima** [comment]
Article for reference: https://blog.windingtree.com/protection-against-illegitimate-booking-requests-d34a54a5fe8b

**Comment by czervenka** [comment]
We are working on this WTip as part of [Spam protection project](https://github.com/orgs/windingtree/projects/4)

**Comment by JirkaChadima** [comment]
I guess we can close this thing: https://developers.windingtree.com/architecture/trust-clues.html
