### ISSUE TITLE
wtip 003 - Check data structure specification for best practices

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wtips#9]
Following a discussion with Adam, we have agreed on two best-practice principles that should guide our approach to designing data structures in general:

1. Do not put data into object keys. This has multiple reasons, one of them being the impossibility of validating key formats in json schema.

2. Try to keep the coupling between individual documents rather loose.

As far as number 1 goes, the current proposal contains several places where data (e.g. flight numbers) are in object keys; maybe this should be reworked.

Regarding number 2, the individual documents are rather tightly coupled through references between them (e.g. segment IDs). I'm not entirely sure it can be improved, though.

**Comment by ondrejchmelar** [comment]
We've removed data from object keys. Tight coupling is something to have on mind when designing more data structures; there is nothing to improve now.
